# Generated by Django 3.0.7 on 2020-06-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200607_1755"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="follow", unique_together=set(),),
    ]
